package antigravity

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	ansiRegex          = regexp.MustCompile(`\x1b\[[0-9;]*[a-zA-Z]`)
	DefaultBlockedEnvs = []string{
		"GMAIL_APP_PASSWORD",
		"GEMINI_API_KEY",
		"GOOGLE_APPLICATION_CREDENTIALS",
		"GCP_PROJECT_ID",
	}
)

// CommandExecutor abstracts command execution with working directory and environment.
type CommandExecutor func(ctx context.Context, dir string, env []string, name string, args ...string) ([]byte, error)

// Runner manages execution of the Antigravity CLI (agy) in non-interactive print mode.
type Runner struct {
	binPath      string
	workspaceDir string
	blockedEnvs  []string
	executor     CommandExecutor
}

// NewRunner creates a new Antigravity CLI runner.
func NewRunner(binPath string) *Runner {
	if strings.TrimSpace(binPath) == "" {
		binPath = "agy"
	}
	return &Runner{
		binPath:     binPath,
		blockedEnvs: DefaultBlockedEnvs,
		executor: func(ctx context.Context, dir string, env []string, name string, args ...string) ([]byte, error) {
			cmd := exec.CommandContext(ctx, name, args...)
			if dir != "" {
				cmd.Dir = dir
			}
			if len(env) > 0 {
				cmd.Env = env
			}
			return cmd.CombinedOutput()
		},
	}
}

// WithWorkspace sets the working directory for agy execution.
func (r *Runner) WithWorkspace(dir string) *Runner {
	r.workspaceDir = dir
	return r
}

// WithExecutor overrides the executor (primarily for testing).
func (r *Runner) WithExecutor(executor CommandExecutor) *Runner {
	r.executor = executor
	return r
}

// WithBlockedEnvs overrides the list of sensitive environment variables to strip.
func (r *Runner) WithBlockedEnvs(blocked []string) *Runner {
	r.blockedEnvs = blocked
	return r
}

// ResolveBinPath finds the executable path for agy, checking common locations if not in PATH.
func ResolveBinPath(binPath string) string {
	cleanPath := strings.TrimSpace(binPath)
	if cleanPath == "" {
		cleanPath = "agy"
	}
	if p, err := exec.LookPath(cleanPath); err == nil {
		return p
	}

	// Candidate fallback paths if running in a restricted PATH environment (like systemd)
	candidates := []string{
		"/usr/local/bin/agy",
		"/usr/bin/agy",
		"/home/emailagent/.local/bin/agy",
	}
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		candidates = append(candidates, filepath.Join(home, ".local", "bin", "agy"))
	}

	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	return cleanPath
}

// ExecutionResult holds response text and conversation ID.
type ExecutionResult struct {
	Response       string
	ConversationID string
}

// BuildArgs constructs CLI arguments for agy execution.
func (r *Runner) BuildArgs(conversationID, prompt string) []string {
	var args []string
	cleanConv := strings.TrimSpace(conversationID)
	if cleanConv != "" {
		args = append(args, "--conversation", cleanConv)
	}
	args = append(args, "--dangerously-skip-permissions", "--output-format", "json", "-p", prompt)
	return args
}

// Execute runs the prompt against agy and returns the generated text and conversation ID.
func (r *Runner) Execute(ctx context.Context, conversationID, prompt string) (*ExecutionResult, error) {
	args := r.BuildArgs(conversationID, prompt)
	cleanEnv := SanitizeEnv(os.Environ(), r.blockedEnvs)
	targetBin := ResolveBinPath(r.binPath)

	out, err := r.executor(ctx, r.workspaceDir, cleanEnv, targetBin, args...)
	if err != nil {
		return nil, fmt.Errorf("agy execution failed: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}

	raw := string(out)
	var cliRes struct {
		ConversationID string `json:"conversation_id"`
		Status         string `json:"status"`
		Response       string `json:"response"`
	}

	trimmed := strings.TrimSpace(raw)
	startIdx := strings.Index(trimmed, "{")
	endIdx := strings.LastIndex(trimmed, "}")
	if startIdx >= 0 && endIdx > startIdx {
		jsonStr := trimmed[startIdx : endIdx+1]
		if err := json.Unmarshal([]byte(jsonStr), &cliRes); err == nil && cliRes.Response != "" {
			return &ExecutionResult{
				Response:       CleanOutput(cliRes.Response),
				ConversationID: cliRes.ConversationID,
			}, nil
		}
	}

	cleanOutput := CleanOutput(raw)
	if cleanOutput == "" {
		cleanOutput = "No response generated by Antigravity."
	}

	return &ExecutionResult{
		Response:       cleanOutput,
		ConversationID: conversationID,
	}, nil
}

// SanitizeEnv strips blocked sensitive variables from an environment list and guarantees a healthy PATH.
func SanitizeEnv(environ []string, blocklist []string) []string {
	blockedMap := make(map[string]bool)
	for _, b := range blocklist {
		blockedMap[strings.ToUpper(strings.TrimSpace(b))] = true
	}

	var result []string
	hasPath := false

	for _, env := range environ {
		parts := strings.SplitN(env, "=", 2)
		if len(parts) > 0 {
			key := strings.ToUpper(strings.TrimSpace(parts[0]))
			if blockedMap[key] {
				continue
			}
			if key == "PATH" {
				hasPath = true
				val := parts[1]
				if !strings.Contains(val, "/usr/local/bin") {
					val = val + ":/usr/local/bin"
				}
				env = parts[0] + "=" + val
			}
		}
		result = append(result, env)
	}

	if !hasPath {
		result = append(result, "PATH=/usr/local/bin:/usr/bin:/bin")
	}

	return result
}

// CleanOutput strips ANSI escape codes and normalizes whitespace.
func CleanOutput(raw string) string {
	stripped := ansiRegex.ReplaceAllString(raw, "")
	return strings.TrimSpace(stripped)
}
