package antigravity

import (
	"context"
	"fmt"
	"os/exec"
	"regexp"
	"strings"
)

var ansiRegex = regexp.MustCompile(`\x1b\[[0-9;]*[a-zA-Z]`)

// CommandExecutor abstracts command execution for testability.
type CommandExecutor func(ctx context.Context, name string, args ...string) ([]byte, error)

// Runner manages execution of the Antigravity CLI (agy) in non-interactive print mode.
type Runner struct {
	binPath  string
	executor CommandExecutor
}

// NewRunner creates a new Antigravity CLI runner.
func NewRunner(binPath string) *Runner {
	if strings.TrimSpace(binPath) == "" {
		binPath = "agy"
	}
	return &Runner{
		binPath: binPath,
		executor: func(ctx context.Context, name string, args ...string) ([]byte, error) {
			cmd := exec.CommandContext(ctx, name, args...)
			return cmd.CombinedOutput()
		},
	}
}

// WithExecutor overrides the executor (primarily for testing).
func (r *Runner) WithExecutor(executor CommandExecutor) *Runner {
	r.executor = executor
	return r
}

// BuildArgs constructs CLI arguments for agy execution.
func (r *Runner) BuildArgs(conversationID, prompt string) []string {
	var args []string
	cleanConv := strings.TrimSpace(conversationID)
	if cleanConv != "" {
		args = append(args, "--conversation", cleanConv)
	}
	args = append(args, "--dangerously-skip-permissions", "-p", prompt)
	return args
}

// Execute runs the prompt against agy and returns the generated text.
func (r *Runner) Execute(ctx context.Context, conversationID, prompt string) (string, error) {
	args := r.BuildArgs(conversationID, prompt)
	out, err := r.executor(ctx, r.binPath, args...)
	if err != nil {
		return "", fmt.Errorf("agy execution failed: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}

	cleanOutput := CleanOutput(string(out))
	if cleanOutput == "" {
		return "No response generated by Antigravity.", nil
	}

	return cleanOutput, nil
}

// CleanOutput strips ANSI escape codes and normalizes whitespace.
func CleanOutput(raw string) string {
	stripped := ansiRegex.ReplaceAllString(raw, "")
	return strings.TrimSpace(stripped)
}
